<a href="https://colab.research.google.com/github/Taniya2711/Data-Analysis-project/blob/main/OR1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
!pip install   --upgrade pulp

#Simplex

In [2]:
from pulp import *
import pandas as pd
import numpy as np

In [20]:
lp_prob=LpProblem('Problem',LpMaximize)

In [21]:
x=LpVariable('x',lowBound=0,cat="Integer")
y=LpVariable('y',lowBound=0,cat="Integer")

In [22]:
lp_prob+=3*x+5*y

In [30]:
lp_prob+=x<=4
lp_prob+=2*y<=12
lp_prob+=3*x+2*y<=18

In [31]:
status=lp_prob.solve()
print([status])


[1]


In [32]:
print(value(x),value(y),value(lp_prob.objective))

2.0 6.0 36.0


#Transportation problem

In [35]:

n_plants=3
n_warehouse=4

In [36]:
cost_matrix=np.array([[10,2,20,11],
                         [12,7,9,20],
                         [4,14,16,18]])

In [37]:
demand=np.array([5,15,15,15])

In [38]:
supply=np.array([15,25,10])

In [39]:
print(cost_matrix)

[[10  2 20 11]
 [12  7  9 20]
 [ 4 14 16 18]]


In [40]:
Trans_prob=LpProblem('Transportation',LpMinimize)

In [41]:
indices=[str(i)+str(j) for j in range (1,n_warehouse+1) for i in range(1,n_plants+1)]

In [43]:
indices.sort()
print(indices)

['11', '12', '13', '14', '21', '22', '23', '24', '31', '32', '33', '34']


In [45]:
DV=LpVariable.matrix("X",indices,cat="Integer",lowBound=0)

In [46]:
X=np.array(DV).reshape(3,4)

In [47]:
print(X)

[[X_11 X_12 X_13 X_14]
 [X_21 X_22 X_23 X_24]
 [X_31 X_32 X_33 X_34]]


In [57]:
from pulp import lpSum
Trans_prob += lpSum(cost_matrix*X)

In [60]:
for i in range(n_plants):
    Trans_prob+= lpSum(X[i][j] for j in range(n_warehouse))<=supply[i]

In [62]:
for j in range(n_warehouse):
    Trans_prob+=lpSum(X[i][j] for i in range (n_plants))>=demand[j]

In [63]:
status=Trans_prob.solve()
print(LpStatus[status])

Optimal


In [67]:
for variables in Trans_prob.variables():
 print(variables.name,"=",variables.value())

X_11 = 0.0
X_12 = 5.0
X_13 = 0.0
X_14 = 10.0
X_21 = 0.0
X_22 = 10.0
X_23 = 15.0
X_24 = 0.0
X_31 = 5.0
X_32 = 0.0
X_33 = 0.0
X_34 = 5.0
